export {
  assignTeamAdmin,
  createGame,
  createSeason,
  createStat,
  createTeam,
  createVenue,
  deleteGame,
  deleteStat,
  deleteTeam,
  deleteVenue,
  endGameFullTime,
  fetchLeagueTeams,
  fetchLeagueVenues,
  fetchManagedHub,
  fetchOwnedLeagues,
  fetchSeasonRoster,
  pauseGame,
  recordSubstitutions,
  resumeGame,
  setMotmAward,
  accreditStat,
  updateGameScore,
  startExtraTime,
  startFirstHalf,
  startHalfTime,
  startSecondHalf,
  updateGame,
  updateLeague,
  updateLeaguePlayer,
  updateSeason,
  updateTeam,
  updateVenue,
  removeLeaguePlayer,
  removeTeamAdmin,
} from "./api";
export type { CreateTeamPayload, UpdateTeamPayload } from "./api";
export { promptBiometricGate } from "./biometric-gate";
export {
  ManageGamesTab,
  ManageLeagueRow,
  ManageAdminTeamRow,
  ManageLoginPrompt,
  ManagePlayersTab,
  ManageSettingsTab,
  ManageTeamsTab,
  ManageVenuesTab,
  ManageKnockoutTab,
  ManageGroupsTab,
  ManageStandingsTab,
  ManageActivityTab,
  TeamFormSheet,
  VenueFormSheet,
  GameControls,
  LiveMinute,
} from "./components";
export {
  useAssignTeamAdmin,
  useCreateGame,
  useCreateSeason,
  useCreateTeam,
  useCreateVenue,
  useAccreditStat,
  useCreateStat,
  useDeleteGame,
  useDeleteStat,
  useDeleteTeam,
  useDeleteVenue,
  useGameTimeActions,
  useUpdateGameScore,
  useLeagueTeams,
  useLeagueVenues,
  useManageLeagueDetail,
  useManagedHub,
  useOwnedLeagues,
  useSeasonRoster,
  useRecordSubstitutions,
  useRemoveLeaguePlayer,
  useRemoveTeamAdmin,
  useSetMotmAward,
  useUpdateLeaguePlayer,
  useUpdateGame,
  useUpdateLeague,
  useUpdateSeason,
  useUpdateStat,
  useUpdateTeam,
  useUpdateVenue,
} from "./hooks";
export { useLiveMinute } from "@/hooks/useLiveMinute";
export { useGamePhaseLabel } from "@/hooks/useGamePhaseLabel";
export { useTransmitGameListener } from "@/lib/transmit";
export type { GameSSEPayload } from "@/lib/transmit";
export { manageKeys } from "./queryKeys";
export type {
  CreateGamePayload,
  CreateSeasonPayload,
  CreateStatPayload,
  CreateVenuePayload,
  CreatedSeason,
  LeagueRosterRow,
  ManagedHub,
  ManagedTeam,
  AdminTeamManaged,
  OwnedLeague,
  RecordSubstitutionItem,
  RecordSubstitutionsPayload,
  RecordSubstitutionsResult,
  TeamAdmin,
  TeamAdminUser,
  UpdateGamePayload,
  UpdateLeaguePayload,
  UpdateSeasonPayload,
  UpdateStatPayload,
  UpdateVenuePayload,
} from "./types";
export {
  GameStatus,
  MatchEventStatName,
  RosterPosition,
  SeasonStatusEnum,
} from "./types";
export {
  applyScoreDelta,
  partitionGames,
  resolveStatTypeId,
  scoresAffectingStat,
} from "./utils/games";
export {
  findLatestUnaccreditedGoal,
  isGoalStat,
  isSubstitutionOffStat,
  isSubstitutionOnStat,
  isUnaccreditedGoal,
  pairSubstitutionEvents,
  partitionGoalStats,
} from "./utils/stats";
export type { PairedSubstitution } from "./utils/stats";
export {
  calculateCurrentMinute,
  formatLiveMinuteLabel,
  isGameClockTicking,
  isGameLivePeriod,
} from "@/lib/game-time";
export type { GameClockFields } from "@/lib/game-time";
